/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taktiktuk;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author wathz
 */
public class Tak extends javax.swing.JFrame {

    int a=0;
    String o1="a";
    String o2="b";
    String o3="c";
    String o4="d";
    String o5="e";
    String o6="f";
    String o7="g";
    String o8="h";
    String o9="i";
    public Tak() {
        initComponents();
        jPanel1.setVisible(false);
        
    }
     
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tak Tik Tuk");
        setBackground(new java.awt.Color(20, 15, 9));
        setForeground(new java.awt.Color(24, 10, 10));

        jPanel1.setBackground(new java.awt.Color(20, 15, 9));

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jMenu1.setText("File");

        jMenuItem1.setForeground(new java.awt.Color(12, 10, 4));
        jMenuItem1.setText("New Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(10, 7, 0));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu2StateChanged(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("How to Play");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (a==0) {
            b1.setText("X");
            a=1;
            o1 = b1.getText();
            if (((o1==o2)&&(o1==o3))|| ((o1==o4)&&(o1==o7))||((o1==o5)&&(o1==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
                    
        } else {
            b1.setText("0");
            a=0;
            o1 = b1.getText();
            if (((o1==o2)&&(o1==o3))|| ((o1==o4)&&(o1==o7))||((o1==o5)&&(o1==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
          }
        
            
            
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (a==0) {
            b2.setText("X");
            a=1;
            o2 = b2.getText();
            if (((o1==o2)&&(o1==o3))|| ((o2==o5)&&(o2==o8))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b2.setText("0");
            a=0;
            o2 = b2.getText();
            if (((o1==o2)&&(o1==o3))|| ((o2==o5)&&(o2==o8))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                    }
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        }
         
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (a==0) {
            b3.setText("X");
            a=1;
            o3 = b3.getText();
            if (((o1==o2)&&(o1==o3))|| ((o3==o6)&&(o3==o9))||((o3==o5)&&(o3==o6))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b3.setText("0");
            a=0;
            o3 = b3.getText();
            if (((o1==o2)&&(o1==o3))|| ((o3==o6)&&(o3==o9))||((o3==o5)&&(o3==o6))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                        
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        }
           
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       if (a==0) {
            b4.setText("X");
            a=1;
            o4 = b4.getText();
            if (((o1==o4)&&(o1==o7))|| ((o4==o5)&&(o4==o6))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b4.setText("0");
            a=0;
            o4 = b4.getText();
            if (((o1==o4)&&(o1==o7))|| ((o4==o5)&&(o4==o6))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (a==0) {
            b5.setText("X");
            a=1;
            o5 = b5.getText();
            if (((o2==o5)&&(o2==o8))|| ((o4==o5)&&(o4==o6))||((o1==o5)&&(o1==o9))||((o3==o5)&&(o3==o7))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
            
            
        } else {
            b5.setText("0");
            a=0;
            o5 = b5.getText();
            if (((o2==o5)&&(o2==o8))|| ((o4==o5)&&(o4==o6))||((o1==o5)&&(o1==o9))||((o3==o5)&&(o3==o7))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (a==0) {
            b6.setText("X");
            a=1;
            o6 = b6.getText();
            if (((o1==o6)&&(o5==o6))|| ((o6==o3)&&(o6==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"x WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b6.setText("0");
            a=0;
            o6 = b6.getText();
            if (((o4==o6)&&(o5==o6))|| ((o6==o3)&&(o6==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
            
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (a==0) {
            b7.setText("X");
            a=1;
            o7 = b7.getText();
            if (((o1==o7)&&(o1==o4))|| ((o7==o8)&&(o7==o9))||((o7==o5)&&(o3==o7))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b7.setText("0");
            a=0;
            o7 = b7.getText();
            if (((o1==o7)&&(o1==o4))|| ((o7==o8)&&(o7==o9))||((o7==o5)&&(o3==o7))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (a==0) {
            b8.setText("X");
            a=1;
            o8 = b8.getText();
            if (((o8==o2)&&(o8==o5))|| ((o8==o7)&&(o8==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"x WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
            
            
        } else {
            b8.setText("0");
            a=0;
            o8 = b8.getText();
            if (((o8==o2)&&(o8==o5))|| ((o8==o7)&&(o8==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (a==0) {
            b9.setText("X");
            a=1;
            o9 = b9.getText();
            if (((o3==o9)&&(o3==o6))|| ((o9==o7)&&(o8==o9))||((o5==o9)&&(o1==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"X WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
            
        } else {
            b9.setText("0");
            a=0;
            o9 = b9.getText();
            if (((o3==o9)&&(o3==o6))|| ((o9==o7)&&(o8==o9))||((o5==o9)&&(o1==o9))) {
                int option= JOptionPane.showConfirmDialog(this,"0 WIns the Game !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
            
                }
                
            }else if ((o1=="X" || o1=="0")&&(o2=="X" || o2=="0")&&(o3=="X" || o3=="0")&&(o5=="X" || o5=="0")&&(o6=="X" || o6=="0")&&(o7=="X" || o7=="0")&&(o8=="X" || o8=="0")&&(o9=="X" || o9=="0")&&(o4=="X" || o4=="0")) {
                    int option= JOptionPane.showConfirmDialog(this,"Game is draw !", "Winner",JOptionPane.OK_OPTION);
                    if (option==JOptionPane.OK_OPTION) {
                        b1.setText(null);
                        b2.setText(null);
                        b3.setText(null);
                        b4.setText(null);
                        b5.setText(null);
                        b6.setText(null);
                        b7.setText(null);
                        b8.setText(null);
                        b8.setText(null);
                        b9.setText(null);
                        a=0;
                        o1="a";
                        o2="b";
                        o3="c";
                        o4="d";
                        o5="e";
                        o6="f";
                        o7="g";
                        o8="h";
                        o9="i";
                    
            
                    } 
                }
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanel1.setVisible(true);
        b1.setText(null);
        b2.setText(null);
        b3.setText(null);
        b4.setText(null);
        b5.setText(null);
        b6.setText(null);
        b7.setText(null);
        b8.setText(null);
        b8.setText(null);
        b9.setText(null);
        a=0;
        o1="a";
        o2="b";
        o3="c";
        o4="d";
        o5="e";
        o6="f";
        o7="g";
        o8="h";
        o9="i";
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int option= JOptionPane.showConfirmDialog(this, "Are you sure You want to Exit?", "Exit Game", JOptionPane.YES_NO_OPTION);
        
        if (option==JOptionPane.YES_OPTION) {
            System.exit(0);
            
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       JOptionPane.showConfirmDialog(this, "Are you sure You want to Exit?", "Exit Game", JOptionPane.CANCEL_OPTION);
        
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2StateChanged

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         JOptionPane.showConfirmDialog(this, "Two players needs to play this game. first plyer is X and second player is 0. Its same like normal Tak Tik Tuk.", "How to Play", JOptionPane.CANCEL_OPTION);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
